### ISSUE TITLE
gui does'nt works 1.13.1

### ISSUE THREAD

**Issue by Yukyxy** [danielntech/miniaturepets#29] opened 2018-09-07 10:59 UTC
Hello 
https://youtu.be/-dnP7Sri0GA
- gui buttons delete / renames / disguises animals / teleport ... does'nt works.

**Comment by NacOJerk** [comment] 2018-09-09 12:28
Are you using plugman ?

**Comment by Yukyxy** [comment] 2018-09-10 11:01
no

**Comment by danielntech** [comment] 2018-09-10 11:06
Please send your DUMP file.

**Comment by Yukyxy** [comment] 2018-09-10 11:07
https://pastebin.com/hqDhCLxk

**Comment by Yukyxy** [comment] 2018-09-10 12:36
This is the file petGUI.yml that buggy...
Material WOOL does'nt works and RED_WOOL too in 1.13.1 => https://pastebin.com/qkBuDKqJ
I tried the APPLE item it works fine now

**Comment by NacOJerk** [comment] 2018-09-15 10:30
Odd maby the name was changed in 1.13

**Comment by BillyGalbreath** [comment] 2018-09-28 12:12
This is caused by the compatibility layer in CraftBukkit on 1.13.x builds. Plugins compiled against 1.12 will still work on 1.13.x, but only when using the `legacy` names.

@Yukyxy set the value to `LEGACY_WOOL` and it should work.

**Comment by danielntech** [comment] 2018-10-06 10:18
This was resolved in recent updates.

**Closed by danielntech** 2018-10-06 10:18 UTC
Labels: BUG
