### ISSUE TITLE
There is a problem with riding in your current MC version.

### ISSUE THREAD

**Issue by andrewkm** [danielntech/miniaturepets#45] opened 2018-09-23 07:24 UTC
Miniature Pets 2.0.3

Running PaperSpigot 1.13.1
Specifically Build #279
https://papermc.io/ci/job/Paper-1.13/

Error: https://pastebin.com/raw/EWCeHxsL

Assuming you guys are still working on pet riding with latest 1.13.1 MC?

**Comment by BillyGalbreath** [comment] 2018-09-27 20:03
```    public static boolean isRidingPossible() {
        try {
            if (getVersion().contains("12")) {
                return getNMS("EntityLiving").getMethod("a", Float.TYPE, Float.TYPE, Float.TYPE) != null && getNMS("EntityInsentient").getMethod("k", Float.TYPE) != null;
            }
            if (getNMS("EntityLiving").getMethod("g", Float.TYPE, Float.TYPE) != null) {
                if (getVersion().contains("8")) {
                    if (getNMS("EntityInsentient").getMethod("k", Float.TYPE) == null) {
                        return false;
                    }
                }
                else if (getNMS("EntityInsentient").getMethod("l", Float.TYPE) == null) {
                    return false;
                }
                return true;
            }
            return false;
        }
        catch (Exception ex) {
            return false;
        }
    }```

Error is caused by this check. In 1.13.x the `k` method is now `o` (or `setAIMoveSpeed` if you use MCP mappings)

**Comment by danielntech** [comment] 2018-09-28 07:03
Thank you for pointing us to the solution, we appreciate it, the update will be released in the upcoming days.
Thanks.

**Closed by danielntech** 2018-09-28 07:03 UTC
Labels: BUG
