### ISSUE TITLE
nms error "No Such Field Exception: networkManager"

### ISSUE THREAD

**Issue by OpalMoonstride** [danielntech/miniaturepets#78] opened 2018-12-31 18:04 UTC
No such field exception on player login; networkManager

```
[09:44:55 WARN]: java.lang.NoSuchFieldException: networkManager
[09:44:55 WARN]: at java.lang.Class.getDeclaredField(Class.java:2070)
[09:44:55 WARN]: at com.kirelcodes.miniaturepets.utils.NMSClassInteracter.getDeclaredField(NMSClassInteracter.java:168)
[09:44:55 WARN]: at com.kirelcodes.miniaturepets.utils.NMSClassInteracter.getDeclaredField(NMSClassInteracter.java:156)
[09:44:55 WARN]: at com.kirelcodes.miniaturepets.packetListeners.PacketInjector.getNetworkManager(PacketInjector.java:67)
[09:44:55 WARN]: at com.kirelcodes.miniaturepets.packetListeners.PacketInjector.addPlayer(PacketInjector.java:37)
[09:44:55 WARN]: at com.kirelcodes.miniaturepets.listener.CoreListener.onPlayerJoin(CoreListener.java:491)
[09:44:55 WARN]: at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor274.execute(Unknown Source)
[09:44:55 WARN]: at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70)
[09:44:55 WARN]: at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78)
[09:44:55 WARN]: at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[09:44:55 WARN]: at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:513)
[09:44:55 WARN]: at net.minecraft.server.v1_13_R2.PlayerList.onPlayerJoin(PlayerList.java:369)
[09:44:55 WARN]: at net.minecraft.server.v1_13_R2.PlayerList.a(PlayerList.java:180)
[09:44:55 WARN]: at net.minecraft.server.v1_13_R2.LoginListener.b(LoginListener.java:170)
[09:44:55 WARN]: at net.minecraft.server.v1_13_R2.LoginListener.tick(LoginListener.java:66)
[09:44:55 WARN]: at net.minecraft.server.v1_13_R2.NetworkManager.a(NetworkManager.java:263)
[09:44:55 WARN]: at net.minecraft.server.v1_13_R2.ServerConnection.c(ServerConnection.java:130)
[09:44:55 WARN]: at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1129)
[09:44:55 WARN]: at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439)
[09:44:55 WARN]: at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:943)
[09:44:55 WARN]: at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:841)
[09:44:55 WARN]: at java.lang.Thread.run(Thread.java:748)
```

Installed v2.1.4 MiniaturePets.jar. 

CMI plugin version: 8.3.0.0
Server version: Spigot 1.13.2-R0.1-SNAPSHOT
Vault version: 1.7.1-b91

*Miniature Pets Dump Link:* https://pastebin.com/5wWKGRm8

**Comment by danielntech** [comment] 2019-01-06 07:54
Please update to the latest version.

**Comment by danielntech** [comment] 2019-01-09 10:48
I can confirm due to several reports that this was fixed with the latest release. If you still encounter issues please reopen this ticket.

**Closed by danielntech** 2019-01-09 10:48 UTC
Labels: REVIEW
